import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { SettingsDrawer } from './SettingsDrawer'
import { AwardPopup } from './AwardPopup'
import { useProgress } from '../lib/ProgressContext'

const links = [
  { to: '/', label: 'Home' },
  { to: '/explore', label: 'Explore IKS' },
  { to: '/awards', label: 'Awards' },
  { to: '/feedback', label: 'Feedback' },
]

export function Layout() {
  const [open, setOpen] = useState(false)
  const [menu, setMenu] = useState(false)
  const { beep } = useProgress()

  return (
    <div className="grain min-h-screen">
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[120] focus:bg-[var(--ember)] focus:px-3 focus:py-2"
      >
        Skip to content
      </a>
      <header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_82%,transparent)] backdrop-blur-xl">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3">
          <NavLink to="/" className="flex items-center gap-3" onClick={() => beep()}>
            <span className="grid h-12 w-12 overflow-hidden rounded-lg bg-[var(--ember)] ring-1 ring-[var(--ember2)]/50">
              <img
                src="/assets/main-logo.png"
                alt="Silver Oaks International School logo"
                className="h-full w-full object-cover"
              />
            </span>
            <span className="leading-tight">
              <span className="block font-display text-2xl tracking-wide">IKS</span>
              <span className="hidden text-[10px] uppercase tracking-[0.22em] text-[var(--mute)] sm:block">
                Silver Oaks
              </span>
            </span>
          </NavLink>
          <nav className="hidden items-center gap-1 md:flex" aria-label="Primary">
            {links.map((l) => (
              <NavLink
                key={l.to}
                to={l.to}
                end={l.to === '/'}
                className={({ isActive }) =>
                  `rounded-full px-4 py-2 text-sm ${isActive ? 'bg-[var(--ember)] text-white' : 'text-[var(--mute)] hover:text-[var(--ink)]'}`
                }
              >
                {l.label}
              </NavLink>
            ))}
          </nav>
          <div className="flex items-center gap-2">
            <button
              className="btn btn-ghost md:hidden"
              aria-expanded={menu}
              aria-label="Open menu"
              onClick={() => setMenu((v) => !v)}
            >
              Menu
            </button>
            <button
              className="btn btn-ghost"
              aria-label="Open settings"
              onClick={() => {
                beep()
                setOpen(true)
              }}
            >
              ⚙
            </button>
          </div>
        </div>
        {menu && (
          <nav className="flex flex-col gap-1 border-t border-[var(--line)] px-4 py-3 md:hidden">
            {links.map((l) => (
              <NavLink
                key={l.to}
                to={l.to}
                end={l.to === '/'}
                onClick={() => setMenu(false)}
                className={({ isActive }) =>
                  `rounded-xl px-3 py-3 ${isActive ? 'bg-[var(--ember)] text-white' : ''}`
                }
              >
                {l.label}
              </NavLink>
            ))}
          </nav>
        )}
      </header>
      <Outlet />
      <footer className="border-t border-[var(--line)] bg-[var(--paper-2)]">
        <div className="mx-auto flex max-w-6xl flex-col items-center gap-4 px-4 py-10 text-center">
        <div className="rounded-2xl bg-[#1a0508] px-6 py-4">
          <img
            src="./assets/logo-white.jpg"
            alt="Silver Oaks International School"
            className="mx-auto h-16 w-auto"
            onError={(e) => {
              e.currentTarget.style.display = 'none'
            }}
          />
        </div>
          <p className="max-w-xl text-sm text-[var(--mute)]">
            <span className="block">
              Silver Oaks International School · Indian Knowledge Systems journey · Character Before
              Competence
            </span>
            <span className="mt-2 block text-xs uppercase tracking-[0.16em] text-[var(--ember2)]">
              Website Planned and Generated by Krishiv Kanjarkar
            </span>
          </p>
        </div>
        <img
          src="./assets/character-before-competence.jpg"
          alt="I choose Character Before Competence"
          className="block h-auto w-full object-cover"
        />
      </footer>
      <SettingsDrawer open={open} onClose={() => setOpen(false)} />
      <AwardPopup />
    </div>
  )
}
